### ISSUE TITLE
Add option to omit data attribute

### ISSUE THREAD

**Issue by chipit24** [hph/stateful-react-container-webpack-plugin#1]
Can you add an option to not include `data-${attribute}="<%= ${variable} %>"` in the output?

**Comment by hph** [comment]
@chipit24 Yeah, I've actually been meaning to do that for a while. I'll keep you posted!

**Comment by hph** [comment]
@chipit24 I just updated the plugin with the `noState` option, which defaults to false. If you set it, you will only get the container element injected.
